import sqlite3
import codecs
import sys
import glob


def main():
    conn = sqlite3.connect(sys.argv[1] + ".db3")

    cursor = conn.cursor()

    i = 0
    line2 = ''

    filenumber = len(glob.glob(sys.argv[1] + '*.sql'))
    ACTIONS = ['INSERT', 'CREATE']
    for i in range(0, filenumber):
        f = codecs.open("{0}_{1:04d}.sql".format(sys.argv[1], i), "r", 'UTF8')
        for line in f:
            if line[0:2] == '--' or len(line.strip()) == 0:
                continue
            if line.strip()[-1] != ';':
                line2 += line
            else:
                line2 += line
                if line2.strip()[0:6] in ACTIONS:
                    try:
                        cursor.execute(line2)
                    except:
                        print(line2)
                line2 = ''
        f.close()
    cursor.close()
    conn.commit()


def help():
    print('''Usage: {0} <SQL Filename Prefix>
Transform SQL scripts generated by ExportSQLCE into a SQLite Database
So if you have SQL_0001.sql, SQL_0002.sql, ..., SQL_0010.sql, \
you'll need to use "{0} SQL"
        '''.format(sys.argv[0]))

if __name__ == '__main__':
    if len(sys.argv) == 2:
        main()
    else:
        help()
